export const BUS_CREATE_REQUEST = "BUS_CREATE_REQUEST";
export const BUS_CREATE_SUCCESS = "BUS_CREATE_SUCCESS";
export const BUS_CREATE_FAIL = "BUS_CREATE_FAIL";
export const BUS_CREATE_RESET = "BUS_CREATE_RESET";

export const BUS_UPDATE_REQUEST = "BUS_UPDATE_REQUEST";
export const BUS_UPDATE_SUCCESS = "BUS_UPDATE_SUCCESS";
export const BUS_UPDATE_FAIL = "BUS_UPDATE_FAIL";
export const BUS_UPDATE_RESET = "BUS_UPDATE_RESET";

export const BUS_DELETE_REQUEST = "BUS_DELETE_REQUEST";
export const BUS_DELETE_SUCCESS = "BUS_DELETE_SUCCESS";
export const BUS_DELETE_FAIL = "BUS_DELETE_FAIL";
export const BUS_DELETE_RESET = "BUS_DELETE_RESET";

export const BUS_LIST_REQUEST = "BUS_LIST_REQUEST";
export const BUS_LIST_SUCCESS = "BUS_LIST_SUCCESS";
export const BUS_LIST_FAIL = "BUS_LIST_FAIL";

export const BUS_GET_REQUEST = "BUS_GET_REQUEST";
export const BUS_GET_SUCCESS = "BUS_GET_SUCCESS";
export const BUS_GET_FAIL = "BUS_GET_FAIL";

export const SAVE_DETAILS = "SAVE_DETAILS";

export const UPDATE_SEAT_TO_BOOKED_REQUEST = "UPDATE_SEAT_TO_BOOKED_REQUEST";
export const UPDATE_SEAT_TO_BOOKED_SUCCESS = "UPDATE_SEAT_TO_BOOKED_SUCCESS";
export const UPDATE_SEAT_TO_BOOKED_FAIL = "UPDATE_SEAT_TO_BOOKED_FAIL";
export const UPDATE_SEAT_TO_BOOKED_RESET = "UPDATE_SEAT_TO_BOOKED_RESET";

export const BUS_RESET_REQUEST = "BUS_RESET_REQUEST";
export const BUS_RESET_SUCCESS = "BUS_RESET_SUCCESS";
export const BUS_RESET_FAIL = "BUS_RESET_FAIL";
export const BUS_RESET_RESET = "BUS_RESET_RESET";
