export const BUS_DEPARTURE_CREATE_REQUEST = "BUS_DEPARTURE_CREATE_REQUEST";
export const BUS_DEPARTURE_CREATE_SUCCESS = "BUS_DEPARTURE_CREATE_SUCCESS";
export const BUS_DEPARTURE_CREATE_FAIL = "BUS_DEPARTURE_CREATE_FAIL";
export const BUS_DEPARTURE_CREATE_RESET = "BUS_DEPARTURE_CREATE_RESET";

export const BUS_DEPARTURE_UPDATE_REQUEST = "BUS_DEPARTURE_UPDATE_REQUEST";
export const BUS_DEPARTURE_UPDATE_SUCCESS = "BUS_DEPARTURE_UPDATE_SUCCESS";
export const BUS_DEPARTURE_UPDATE_FAIL = "BUS_DEPARTURE_UPDATE_FAIL";
export const BUS_DEPARTURE_UPDATE_RESET = "BUS_DEPARTURE_UPDATE_RESET";

export const BUS_DEPARTURE_DELETE_REQUEST = "BUS_DEPARTURE_DELETE_REQUEST";
export const BUS_DEPARTURE_DELETE_SUCCESS = "BUS_DEPARTURE_DELETE_SUCCESS";
export const BUS_DEPARTURE_DELETE_FAIL = "BUS_DEPARTURE_DELETE_FAIL";
export const BUS_DEPARTURE_DELETE_RESET = "BUS_DEPARTURE_DELETE_RESET";

export const BUS_DEPARTURE_LIST_REQUEST = "BUS_DEPARTURE_LIST_REQUEST";
export const BUS_DEPARTURE_LIST_SUCCESS = "BUS_DEPARTURE_LIST_SUCCESS";
export const BUS_DEPARTURE_LIST_FAIL = "BUS_DEPARTURE_LIST_FAIL";

export const BUS_DEPARTURE_GET_REQUEST = "BUS_DEPARTURE_GET_REQUEST";
export const BUS_DEPARTURE_GET_SUCCESS = "BUS_DEPARTURE_GET_SUCCESS";
export const BUS_DEPARTURE_GET_FAIL = "BUS_DEPARTURE_GET_FAIL";

